server:
  port: 9100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://my-auth-server.com
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      password:

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
