spring:
  application:
    name: chatroom
  datasource:
    generate-unique-name: false
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:h2:mem:chat_app
  h2:
    console:
      enable: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: false
#    open-in-view: false
#    hibernate:
#      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG

