#server.port=9001
#spring.application.name=chatroom
#
#spring.datasource.url=jdbc:mysql://localhost:3306/chatroom
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop


server:
  port: 9001

spring:
  application:
    name: chatroom
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:my_app
  h2:
    console:
      enable: true
      path: '/h2'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG