server:
  port: 9091

spring:
  application:
    name: chatroom
  datasource:
    url: jdbc:h2:mem:chat_app
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enable: true
      path: /h2

#logging:
#  level:
#    org.hibernate.SQL: DEBUG

cors.allowed.origins: "${CORS_ALLOWED_ORIGINS}"
